# Generated by Django 3.2.9 on 2021-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=15, verbose_name='短链接')),
                ('name', models.CharField(max_length=20, verbose_name='文件名')),
                ('download_url', models.TextField(verbose_name='服务器下载链接')),
                ('file_path', models.FileField(upload_to='', verbose_name='服务器路径')),
                ('time', models.DateTimeField(verbose_name='处理时间')),
            ],
        ),
    ]
